# Generated by Django 2.2.13 on 2020-06-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200615_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ddescription',
            new_name='description',
        ),
    ]
